### ISSUE TITLE
How do I solve this?

### ISSUE THREAD

**Issue by jamesmatarazzo1** [e3kskoy7wqk/Chromium-for-windows-7#24]
In all Chromium versions of this site this insufficient memory error appears, it's something annoying.

![Image](https://github.com/user-attachments/assets/33698f7d-97c4-42c5-b2ce-b75f18855d4c)

**Comment by e3kskoy7wqk** [comment]
How much memory does your computer have?

Have you tried [this version](https://github.com/e3kskoy7wqk/Chromium-for-windows-7/releases/download/122.0.6261.34/mini_installer.exe)? If this version does not have the issue, then the problem might be resolvable. Otherwise, I won't be able to fix it.

**Comment by jamesmatarazzo1** [comment]
> Quanta memória seu computador tem?
> 
> Você tentou [esta versão](https://github.com/e3kskoy7wqk/Chromium-for-windows-7/releases/download/122.0.6261.34/mini_installer.exe) ? Se esta versão não tiver o problema, então o problema pode ser solucionável. Caso contrário, não poderei consertá-lo.

This one works, but I wanted to use recent versions.

**Comment by e3kskoy7wqk** [comment]
If possible, I would appreciate it if you could help test to determine from which version this issue started.

Additionally, I am very curious about how much memory is installed on your machine.

**Comment by jamesmatarazzo1** [comment]
I have 4gb of ram. This problem occurs on all 130 versions of Chromium, that's what I can say. From versions 120 this does not happen.

**Comment by ZepopaOwleMukasa** [comment]
@e3kskoy7wqk 

For what it matters, I've used to have the same issue on older releases of 13x when using Google Earth and selecting the highest quality assets. Tab just crashed like the picture in the issues description. But this has been fixed some time ago, not sure what release that did it though. It also wasn't a memory issue since I'm using 32gb.

@jamesmatarazzo1 

Are you using the 32-bit or 64-bit release? If this happens on 64-bit, switch to 32-bit (up until a proper fix is found) since it has a much lower memory footprint.

**Comment by e3kskoy7wqk** [comment]
All I know is that after a certain version, the amount of memory used by the browser significantly increased. I suspect this might be causing the issue.

**Comment by e3kskoy7wqk** [comment]
@jamesmatarazzo1 To be honest, I don't know exactly where the problem lies, and I need your help to pinpoint it.

Specifically:
1. Clear the `%LOCALAPPDATA%\Chromium` folder.
2. Download the latest version of Chromium [here](https://github.com/e3kskoy7wqk/Chromium-for-windows-7/releases/tag/135.0.7048.1).
3. Launch Chromium and check if the issue occurs. If the issue appears, close Chromium and zip all the .dmp files in `%LOCALAPPDATA%\Chromium\User Data\Crashpad\reports`, then upload them here.

Note: You can directly enter `%LOCALAPPDATA%\Chromium` and `%LOCALAPPDATA%\Chromium\User Data\Crashpad\reports` in the address bar of File Explorer.

**Comment by jamesmatarazzo1** [comment]
I installed the latest version and still have the same problem.

[5dc50c86-7ba6-4684-bfeb-5b79c1f011f3.dmp](https://github.com/user-attachments/files/19063733/5dc50c86-7ba6-4684-bfeb-5b79c1f011f3.dmp)
[45b58c30-dec3-4b57-ac84-4a00a6910fda.dmp](https://github.com/user-attachments/files/19063731/45b58c30-dec3-4b57-ac84-4a00a6910fda.dmp)
[48a092e3-8144-446a-bfd6-058e78a3402c.dmp](https://github.com/user-attachments/files/19063741/48a092e3-8144-446a-bfd6-058e78a3402c.dmp)
[57ba738c-87c2-4588-ac75-6eb72c145f54.dmp](https://github.com/user-attachments/files/19063742/57ba738c-87c2-4588-ac75-6eb72c145f54.dmp)
[58fe7d23-7815-4779-b248-1a4fea298b91.dmp](https://github.com/user-attachments/files/19063734/58fe7d23-7815-4779-b248-1a4fea298b91.dmp)
[63a4a080-6be3-4681-abd3-e90a4328426e.dmp](https://github.com/user-attachments/files/19063744/63a4a080-6be3-4681-abd3-e90a4328426e.dmp)
[96c1e594-354d-40e3-ab46-475c9adae7ec.dmp](https://github.com/user-attachments/files/19063746/96c1e594-354d-40e3-ab46-475c9adae7ec.dmp)
[a5a40fb9-3e86-4773-990e-a96da7802973.dmp](https://github.com/user-attachments/files/19063737/a5a40fb9-3e86-4773-990e-a96da7802973.dmp)
[a815db0f-8e06-48b2-bd79-82b34be92260.dmp](https://github.com/user-attachments/files/19063739/a815db0f-8e06-48b2-bd79-82b34be92260.dmp)
[ad19a6be-655a-47ac-9289-ed95e5939f2e.dmp](https://github.com/user-attachments/files/19063738/ad19a6be-655a-47ac-9289-ed95e5939f2e.dmp)
[d17fb503-5311-4d3a-942b-2ea5e9674efb.dmp](https://github.com/user-attachments/files/19063740/d17fb503-5311-4d3a-942b-2ea5e9674efb.dmp)
[ed9af5f4-73fc-4106-8fb2-c9ed43c93a37.dmp](https://github.com/user-attachments/files/19063743/ed9af5f4-73fc-4106-8fb2-c9ed43c93a37.dmp)
[ef7d9f03-77e2-4587-812a-e2fab07ded81.dmp](https://github.com/user-attachments/files/19063735/ef7d9f03-77e2-4587-812a-e2fab07ded81.dmp)
[ef6561c1-5270-437e-83f4-65656110f32f.dmp](https://github.com/user-attachments/files/19063732/ef6561c1-5270-437e-83f4-65656110f32f.dmp)
[0a0c36f9-2cb6-4cff-b9a1-8ed8fbfbfd8c.dmp](https://github.com/user-attachments/files/19063736/0a0c36f9-2cb6-4cff-b9a1-8ed8fbfbfd8c.dmp)
[0a68e372-15a1-4f53-bc91-4c315d469a17.dmp](https://github.com/user-attachments/files/19063730/0a68e372-15a1-4f53-bc91-4c315d469a17.dmp)
[4d2102a7-8c5f-40a3-a88b-5a91874c8283.dmp](https://github.com/user-attachments/files/19063745/4d2102a7-8c5f-40a3-a88b-5a91874c8283.dmp)

**Comment by jamesmatarazzo1** [comment]
> Instalei a versão mais recente e ainda tenho o mesmo problema.
> 
> [5dc50c86-7ba6-4684-bfeb-5b79c1f011f3.dmp ](https://github.com/user-attachments/files/19063733/5dc50c86-7ba6-4684-bfeb-5b79c1f011f3.dmp) [45b58c30-dec3-4b57-ac84-4a00a6910fda.dmp ](https://github.com/user-attachments/files/19063731/45b58c30-dec3-4b57-ac84-4a00a6910fda.dmp) [48a092e3-8144-446a-bfd6-058e78a3402c.dmp ](https://github.com/user-attachments/files/19063741/48a092e3-8144-446a-bfd6-058e78a3402c.dmp) [57ba738c-87c2-4588-ac75-6eb72c145f54.dmp ](https://github.com/user-attachments/files/19063742/57ba738c-87c2-4588-ac75-6eb72c145f54.dmp) [58fe7d23-7815-4779-b248-1a4fea298b91.dmp ](https://github.com/user-attachments/files/19063734/58fe7d23-7815-4779-b248-1a4fea298b91.dmp) [63a4a080-6be3-4681-abd3-e90a4328426e.dmp ](https://github.com/user-attachments/files/19063744/63a4a080-6be3-4681-abd3-e90a4328426e.dmp) [96c1e594-354d-40e3-ab46-475c9adae7ec.dmp ](https://github.com/user-attachments/files/19063746/96c1e594-354d-40e3-ab46-475c9adae7ec.dmp) [a5a40fb9-3e86-4773-990e-a96da7802973.dmp ](https://github.com/user-attachments/files/19063737/a5a40fb9-3e86-4773-990e-a96da7802973.dmp) [a815db0f-8e06-48b2-bd79-82b34be92260.dmp ](https://github.com/user-attachments/files/19063739/a815db0f-8e06-48b2-bd79-82b34be92260.dmp) [ad19a6be-655a-47ac-9289-ed95e5939f2e.dmp ](https://github.com/user-attachments/files/19063738/ad19a6be-655a-47ac-9289-ed95e5939f2e.dmp) [d17fb503-5311-4d3a-942b-2ea5e9674efb.dmp ](https://github.com/user-attachments/files/19063740/d17fb503-5311-4d3a-942b-2ea5e9674efb.dmp) [ed9af5f4-73fc-4106-8fb2-c9ed43c93a37.dmp ](https://github.com/user-attachments/files/19063743/ed9af5f4-73fc-4106-8fb2-c9ed43c93a37.dmp) [ef7d9f03-77e2-4587-812a-e2fab07ded81.dmp ](https://github.com/user-attachments/files/19063735/ef7d9f03-77e2-4587-812a-e2fab07ded81.dmp) [ef6561c1-5270-437e-83f4-65656110f32f.dmp ](https://github.com/user-attachments/files/19063732/ef6561c1-5270-437e-83f4-65656110f32f.dmp) [0a0c36f9-2cb6-4cff-b9a1-8ed8fbfbfd8c.dmp ](https://github.com/user-attachments/files/19063736/0a0c36f9-2cb6-4cff-b9a1-8ed8fbfbfd8c.dmp) [0a68e372-15a1-4f53-bc91-4c315d469a17.dmp ](https://github.com/user-attachments/files/19063730/0a68e372-15a1-4f53-bc91-4c315d469a17.dmp) [4d2102a7-8c5f-40a3-a88b-5a91874c8283.dmp](https://github.com/user-attachments/files/19063745/4d2102a7-8c5f-40a3-a88b-5a91874c8283.dmp)

**Comment by jamesmatarazzo1** [comment]
> [@jamesmatarazzo1](https://github.com/jamesmatarazzo1) To be honest, I don't know exactly where the problem lies, and I need your help to pinpoint it.
> 
> Specifically:
> 
> 1. Clear the `%LOCALAPPDATA%\Chromium` folder.
> 2. Download the latest version of Chromium [here](https://github.com/e3kskoy7wqk/Chromium-for-windows-7/releases/tag/135.0.7048.1).
> 3. Launch Chromium and check if the issue occurs. If the issue appears, close Chromium and zip all the .dmp files in `%LOCALAPPDATA%\Chromium\User Data\Crashpad\reports`, then upload them here.
> 
> Note: You can directly enter `%LOCALAPPDATA%\Chromium` and `%LOCALAPPDATA%\Chromium\User Data\Crashpad\reports` in the address bar of File Explorer.

I've already sent the files up there

**Comment by e3kskoy7wqk** [comment]
Please install "Update for Windows 7 (KB3080149)":
x64: https://www.microsoft.com/en-us/download/details.aspx?id=48636
x86: https://www.microsoft.com/en-us/download/details.aspx?id=48638

**Comment by jamesmatarazzo1** [comment]
> Please install "Update for Windows 7 (KB3080149)": x64: https://www.microsoft.com/en-us/download/details.aspx?id=48636 x86: https://www.microsoft.com/en-us/download/details.aspx?id=48638

You are a genius! After I installed this update the browser is now working without this error.

**Comment by ZepopaOwleMukasa** [comment]
@jamesmatarazzo1 

If everything works properly now and no other issues cropped up, don't forget to close the issue.
